version: '3.8'

services:
  # Backend Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: raktconnect-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - raktconnect-network

  # Frontend Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: raktconnect-client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.vite
    depends_on:
      - server
    networks:
      - raktconnect-network

networks:
  raktconnect-network:
    driver: bridge
